version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  memcached:
    image: memcached
  chrome_driver:
    image: verba/docker-chromedriver:latest
    shm_size: 1gb
    privileged: true
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ''
  elasticsearch24:
    image: elasticsearch:2.4
    ports:
      - 9201:9200
      - 9300:9300
    environment:
      discovery.type: single-node
